os: osx
osx_image: xcode11.3
language: swift
script: xcodebuild clean build test -workspace QuizApp.xcworkspace -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.2,name=iPhone X" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
